env:
  UPSTREAM_REPOSITORY: git@github.com:egoritschool/checker_test.git
name: GitHub Actions Demo
on: [push]
jobs:
  fetch-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - run: pytest
